### ISSUE TITLE
list stacks command

### ISSUE THREAD

**Issue by jwilson8767** [Kotaimen/awscfncli#1]
I **love** awscfncli! Thanks so much for making this!

I'd like a way to list existing stacks (whether or not they have stack configs). The AWS CLI's `list-stacks` shows all stacks that ever existed and it's not very useful.

**Comment by Kotaimen** [comment]
@GlieseRay I missed this, I think its a simple request, plz consider it in our "remake" attempt.

**Comment by GlieseRay** [comment]
Well noted.

**Comment by Kotaimen** [comment]
Use `aws cloudformation list-stacks`
