### ISSUE TITLE
New CLI

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#10]
Purposing new CLI:

Before:

    cfn stack update --override-policy=ALLOW_ALL

After:

    cfn-cli -f CONFIG_FILE -s STACK_SELECTOR update --override-policy=ALLOW_ALL

Major changes:

- [x] `cfn` -> `cfn-cli`
- [x] Config file and stack selection move to click options
- [x] Use a stack selector to select stacks in the configuration file
     - Purposing `STAGE_PATTERN.STACK_PATTERN`
     - Default is `Default.*`
- [x] "Collapse" command subcommand structure to use only commands, eg:
     - `stack deploy` -> `deploy`
     - `stack update` -> `update`
     - `changeset sync` -> `sync`
- [ ] Autocomplete (depends on click support)

**Comment by GlieseRay** [comment]
I think 
```
cfn-cli -f CONFIG_FILE stack -s stagename.stackname deploy
cfn-cli -f CONFIG_FILE config list
```
may be more straight forward.

**Comment by Kotaimen** [comment]
`stack` subcommands will not be collapsed, only `changeset sync`
