### ISSUE TITLE
Exception when specified TerminationProtection parameter

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#13]
Exception raised:

    NotImplementedError: Termination protection is not supported for current version of boto. Please upgrade to a new version.

Condition:
- Specified TerminationProtection parameter,
- Executing `cfn-cli sync` command,
- And the stack is not yet created (`changeset_type == 'CREATE'`)

**Comment by Kotaimen** [comment]
When a stack is rolled back with termination protection on, there is no way to disable it.
(not reopen the issue since this is a rare case)

**Comment by Kotaimen** [comment]
Not fixed, another exception is thrown:
```
$ cfn-cli -f samples/annotated-sample-confg.yml sync
Develop.DDBTable1
Generated ChangeSet name DynamoDbTable1-94c53358-452c-11e8-95d7-8c859082dfb2
ChangeSet Type: CREATE
Setting Termination Protection to "False"
An error occurred (ValidationError) when calling the UpdateTerminationProtection operation: Stack [DynamoDbTable1] does not exist
Aborted!
```

**Comment by Kotaimen** [comment]
TerminationProtection seems not working in `stack deploy` command.

**Comment by GlieseRay** [comment]
I tested on the sample config. It works. So please tell me more about the condition and config you use.
