### ISSUE TITLE
Return proper `ERRORLEVEL` / `$?` values

### ISSUE THREAD

**Issue by mkielar** [Kotaimen/awscfncli#17]
Let's say I'm running the command like this:
```
cfn changeset execute ./stack-config.yaml dummy-changeset
```

Then it fails with:
```
Region: eu-west-2
Stack Name: dev-stack
Template: C:\repositories\cloudformation\dev\master.yaml.packaged
An error occurred (ChangeSetNotFound) when calling the ExecuteChangeSet operation: ChangeSet [dummy-changeset] does not exist
```

The issue is, the `%ERRORLEVEL%` is `0` in that case in `cmd.exe`, and similarly under `bash`, the `$?` is also `0`. This makes it hard to implement fail-fast bash scripts...

Above has been tested on Python 3.6.4 in Windows 10 with `cmd.exe` and Cygwin Bash.

**Comment by Kotaimen** [comment]
@GlieseRay plz take a look, it seems the decorator for pretty print stack exceptions hide the error...
This problem may also exists in 2.0 branch.

**Comment by Kotaimen** [comment]
It seems to be a bug in the boto3 exception pretty print handler:

```diff 
 def boto3_exception_handler(f):
     """Capture and pretty print exceptions"""
 
     @wraps(f)
     def wrapper(*args, **kwargs):
         try:
             return f(*args, **kwargs)
         except (botocore.exceptions.ClientError,
                 botocore.exceptions.WaiterError,
                 botocore.exceptions.ValidationError,
                 botocore.exceptions.ParamValidationError,
                 ) as e:
             click.secho(str(e), fg='red')
+            raise click.Abort
         except ConfigError as e:
             click.secho(str(e), fg='red')
-        except KeyboardInterrupt as e:
-            click.secho('Aborted.', fg='red')
+            raise click.Abort


```

Click will return exit status `1` when handling `Abort` exception.

@GlieseRay Please try this on 0.x, I'm testing on v2 branch, which is more complicated since not all commands aborts after caught an exception.

**Comment by GlieseRay** [comment]
I tested on the 0.x version, It's the same problem. I will make a hot fix for that.
