### ISSUE TITLE
Costs

### ISSUE THREAD

**Issue by jwilson8767** [Kotaimen/awscfncli#2]
The AWS CLI has an [estimate-template-costs](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/estimate-template-cost.html) command, and I think it would be awesome to be able to do `cfn stack costs` that would:
- estimate costs of stacks using the `estimate-template-costs` api
- evaluate actual costs incurred by the given stack (even if just on a monthly basis).

I could probably implement the estimates, but I don't know enough about the AWS billing apis to know if the second part is even possible, any ideas?

**Comment by GlieseRay** [comment]
@jwilson8767 Thanks for your advice.

> estimate costs of stacks using the estimate-template-costs api.
I did some research and found that AWS CloudFormation may have some issues of handling cost estimation of template with **nested stacks**. Templates with nested stack resulted a 0 cost estimation. The estimation works fine with plain templates. We'll consider adding this functionality in the next release.

>  evaluate actual costs incurred by the given stack (even if just on a monthly basis).
It seems AWS has not providing any billing api yet. Programmatic accessing billing data can only be achieved by analyzing the billing data (if enabled) on s3, which may be a little too complex for a small tool like this.

**Comment by jwilson8767** [comment]
@GlieseRay Roger on the second point. On the first, does that mean that resource like elastic beanstalk environments aren't evaluated for cost either?

**Comment by GlieseRay** [comment]
@jwilson8767 It means that if you use **AWS::CloudFormation::Stack** resource in your template, the cost of this nested stack are not  evaluated.

**Comment by GlieseRay** [comment]
Added cost command in release 0.5.1.

**Comment by jwilson8767** [comment]
Thanks so much!
