### ISSUE TITLE
The boolean value "True" with capitalized "T" does not work in the configuration file

### ISSUE THREAD

**Issue by GlieseRay** [Kotaimen/awscfncli#30]
For example
```
EnableTerminationProtection: True (not work)
EnableTerminationProtection: true (works)
```

**Comment by Kotaimen** [comment]
What's the status of this issue?

Now I'm writing:
```yaml 
EnableTerminationProtection: True
```
We should make `True`, `true`, `yes`, `on` both work in this condition.

And we shouldn't print out the red error text since `TerminationProtection` is not an error.

**Comment by GlieseRay** [comment]
This could be closed now, seems fixed

Agreed, we should make all this "yes" value work.
