### ISSUE TITLE
The awscfncli "Tutorial" documentation website is throwing 404 error.

### ISSUE THREAD

**Issue by ouelletandrebni** [Kotaimen/awscfncli#5]
The website https://kotaimen.github.io/awscfncli/ containing the awscfncli Tutorial documentation is throwing a 404 error.

![awscfncli-tutorial-web-doc-error](https://user-images.githubusercontent.com/25958748/37835115-289010e0-2e8e-11e8-91b1-2ecdca4d59da.png)

**Comment by GlieseRay** [comment]
New document and tutorial  will be published soon in 2.0 release

**Comment by GlieseRay** [comment]
GitHub Pages requires that we add a `doc` folder in the repository and move our documents there.

**Comment by Kotaimen** [comment]
GitHub Pages is removed.
