### ISSUE TITLE
Update configure file version.

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#54]

**Comment by Kotaimen** [comment]
Cross stack reference is supported in config file version 3.

@GlieseRay :
- [ ] For `2.0.x` release, reading a version 3 config file causes error, even it don't use new version features.
- [ ] For `2.1` release: only version 3 config file supports cross stack reference.

@Kotaimen 
- [ ] By default, `cfn-cli generate` will create a version 3 config.
- [ ] Update sample configure files to use version 3.

**Comment by GlieseRay** [comment]
Fixed on develop branch
