### ISSUE TITLE
Root template not getting uploaded when `Package: True`

### ISSUE THREAD

**Issue by Kotaimen** [Kotaimen/awscfncli#55]
It'll be a good feature when template size exceeding 64k.

**Comment by GlieseRay** [comment]
1. When package is true, cfn-cli should upload root template if size > 64K
2. When package is true, cfn-cli should raise error when template path is a remote resource
3. When package is false, no upload happens, show errors when size > 64K

**Comment by Kotaimen** [comment]
Note: the size limit of template body is 51200 bytes, which is 50K.

**Comment by Kotaimen** [comment]
Fixed by fd5ee2448d5f454fbffcb1c0dfb9bc056ecd4026
