### ISSUE TITLE
Upgrade jsonschema?

### ISSUE THREAD

**Issue by alytle** [Kotaimen/awscfncli#80]
Is there any reason we can't use jsonschema 3? This requirement:  'jsonschema>=2.6.0,<3', is in conflict with a bunch of other useful tools (cfn-lint for one).

Can we upgrade, or is it a breaking change?

**Comment by Kotaimen** [comment]
Hi,  

I think we don't really care the version of jsonschema, I'll try to remove the v3 limit and release a new version, thanks!

**Comment by Kotaimen** [comment]
requirements changed to `jsonschema>=2.6.0`
